/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package p2;

/**
 *
 * @author chris
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnMas = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btnMenos = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnPor = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btnDividir = new javax.swing.JButton();
        bnt0 = new javax.swing.JButton();
        btnComa = new javax.swing.JButton();
        btnResultado = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn1.setText("1");
        getContentPane().add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 70, -1));
        btn1.getAccessibleContext().setAccessibleName("btn!");

        btn2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn2.setLabel("2");
        getContentPane().add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 70, -1));

        btn3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn3.setText("3");
        getContentPane().add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 70, -1));

        btnMas.setBackground(new java.awt.Color(255, 153, 51));
        btnMas.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnMas.setText("+");
        btnMas.setBorderPainted(false);
        btnMas.setName(""); // NOI18N
        getContentPane().add(btnMas, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 70, -1));

        btn4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn4.setText("4");
        getContentPane().add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 70, -1));

        btn5.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn5.setText("5");
        getContentPane().add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 70, -1));

        btn6.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn6.setText("6");
        getContentPane().add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 70, -1));

        btnMenos.setBackground(new java.awt.Color(255, 153, 51));
        btnMenos.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnMenos.setText("-");
        btnMenos.setBorderPainted(false);
        btnMenos.setName(""); // NOI18N
        getContentPane().add(btnMenos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 70, -1));

        btn7.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn7.setText("7");
        getContentPane().add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 70, -1));

        btn8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn8.setText("8");
        getContentPane().add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 70, -1));

        btn9.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn9.setText("9");
        getContentPane().add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 70, -1));

        btnPor.setBackground(new java.awt.Color(255, 153, 51));
        btnPor.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnPor.setText("*");
        btnPor.setBorderPainted(false);
        btnPor.setName(""); // NOI18N
        getContentPane().add(btnPor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 70, -1));

        btnBorrar.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        btnBorrar.setText("AC");
        getContentPane().add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 70, 50));

        btn11.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        btn11.setText("+/-");
        getContentPane().add(btn11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 70, 50));

        btn12.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btn12.setText("%");
        getContentPane().add(btn12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 70, -1));

        btnDividir.setBackground(new java.awt.Color(255, 153, 51));
        btnDividir.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnDividir.setText("/");
        btnDividir.setBorderPainted(false);
        btnDividir.setName(""); // NOI18N
        getContentPane().add(btnDividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 70, -1));

        bnt0.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        bnt0.setText("0");
        getContentPane().add(bnt0, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 140, -1));

        btnComa.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnComa.setText(",");
        getContentPane().add(btnComa, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 70, -1));

        btnResultado.setBackground(new java.awt.Color(255, 153, 51));
        btnResultado.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnResultado.setText("=");
        btnResultado.setBorderPainted(false);
        btnResultado.setName(""); // NOI18N
        getContentPane().add(btnResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 70, -1));

        jTextField1.setBackground(new java.awt.Color(51, 51, 51));
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnComa;
    private javax.swing.JButton btnDividir;
    private javax.swing.JButton btnMas;
    private javax.swing.JButton btnMenos;
    private javax.swing.JButton btnPor;
    private javax.swing.JButton btnResultado;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
